export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const FETCH_BRANCHES = 'FETCH_BRANCHES';
export const GET_BRANCH = 'GET_BRANCH';

export const FETCH_TEACHERS = 'FETCH_TEACHERS';
export const FETCH_TEACHERS_BY_BRANCH = 'FETCH_TEACHERS_BY_BRANCH';

export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const FETCH_STUDENTS_BY_BRANCH = 'FETCH_STUDENTS_BY_BRANCH';

export const FETCH_TEACHER_ATTENDANCES = 'FETCH_TEACHER_ATTENDANCES';
