export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

export const FETCH_BRANCHES = "FETCH_BRANCHES";
export const GET_BRANCH = "GET_BRANCH";

export const FETCH_TEACHER = "FETCH_TEACHER";
export const FETCH_TEACHERS = "FETCH_TEACHERS";
export const FETCH_TEACHERS_BY_BRANCH = "FETCH_TEACHERS_BY_BRANCH";
export const REMOVE_TEACHERS_BY_BRANCH = "REMOVE_TEACHERS_BY_BRANCH";

export const FETCH_STUDENT = "FETCH_STUDENT";
export const FETCH_STUDENTS = "FETCH_STUDENTS";
export const FETCH_STUDENTS_BY_BRANCH = "FETCH_STUDENTS_BY_BRANCH";
export const REMOVE_STUDENTS_BY_BRANCH = "REMOVE_STUDENTS_BY_BRANCH";

export const FETCH_STUDENT_ATTENDANCES = "FETCH_STUDENT_ATTENDANCES";
export const FETCH_TEACHER_ATTENDANCES = "FETCH_TEACHER_ATTENDANCES";

export const FETCH_ADMIN = "FETCH_ADMIN";
export const FETCH_ADMINS = "FETCH_ADMINS";
export const FETCH_EDIT_ADMIN = "FETCH_EDIT_ADMIN";

export const FETCH_FEATURE_FLAG = "FETCH_FEATURE_FLAG";

export const ADMIN_LOGGED_OUT = "ADMIN_LOGGED_OUT";
